### ISSUE TITLE
error in running the example_data

### ISSUE THREAD

**Issue by natlasy** [ajitjohnson/imsig#1]
Hi,

I'm getting an error in running the 'imsig' package as below:

> cell_abundance = imsig(exp = example_data, r = 0.7)
Error in sig[sig$gene %in% as.character(g), ] : 
  incorrect number of dimensions

The example_data looks fine though:

> dim(example_data)
[1] 568  60
> head(example_data, n=6)
      GSM512479.CEL GSM512480.CEL GSM512481.CEL GSM512482.CEL GSM512483.CEL
AFF3       342.4006      52.88693      78.28706      101.1696      43.63739
BANK1     2535.4058     280.72550     498.01262      390.2110     697.87245
BLK        814.3128     132.36280     304.39403      304.8484     264.01830
BTLA       391.7088     152.33024     119.84629      202.0018     255.36544
CCR6       537.1195     153.71538     154.45685      254.8858     175.81826
CD180      821.2340     296.36957     234.71300      273.3661     353.07089

Any idea?

Thanks,
natlasy

**Comment by ajitjohnson** [comment]
Hi Natlasy,
Sorry that you are having this issue. I am not able to reproduce your error. 
This works perfectly for me:
> library("imsig")
> cell_abundance = imsig(exp = example_data, r = 0.7)
Did you install the package from CRAN, like- install.packages("imsig")?

**Comment by natlasy** [comment]
Thanks for your quick reply.

Yes. I installed the package from CRAN  with no error as below:

> install.packages("imsig")
Installing package into ‘/home/natlasy/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://ftp.gwdg.de/pub/misc/cran/src/contrib/imsig_1.0.0.tar.gz'
Content type 'application/octet-stream' length 265039 bytes (258 KB)
==================================================
downloaded 258 KB

* installing *source* package ‘imsig’ ...
** package ‘imsig’ successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (imsig)

The downloaded source packages are in
	‘/tmp/RtmpwsAUca/downloaded_packages’



My R version is as below:

> R.version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          3.1                         
year           2016                        
month          06                          
day            21                          
svn rev        70800                       
language       R                           
version.string R version 3.3.1 (2016-06-21)
nickname       Bug in Your Hair  


Could it be an incompatibility with R version issue?

Best,
natlasy

**Comment by ajitjohnson** [comment]
Hi Natlasy,
The version does not seem to be an issue. I downloaded R3.3.1 and tested. It works fine (See below). 
I think it might be something specific to your system. Can you try it on a different system? Although I tested it now on a windows machine, I have had previously tested the package on a mac and it works. Let me know if it works. Thanks.

> library(imsig)
> cell_abundance = imsig(exp = example_data, r = 0.7)
> head(cell_abundance)[1:3]
                           B cells Interferon Macrophages
GSM512532.CEL 102.56179   1230.431    703.5092
GSM512506.CEL 154.47258   2671.506   1095.1257
GSM512524.CEL 101.89446   1723.283    857.7853
GSM512521.CEL 109.79391   1981.511    948.1081
GSM512519.CEL 128.61854   2044.586   1038.1472
GSM512534.CEL  94.22661   1576.260    994.5554

> version                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          3.1                         
year           2016                        
month          06                          
day            21                          
svn rev        70800                       
language       R                           
version.string R version 3.3.1 (2016-06-21)
nickname       Bug in Your Hair

**Comment by natlasy** [comment]
All right. I tried it on another system with newer version of R and it worked. Then I just got back to the original system and closed the current running session of old R which I first did install the package on it and opened a new session and now it works !! So seemed I had to close/re-open the R.

But when I applied it on my dataset, it is giving me the below error:

> cell_abundance = imsig(exp = data, r = 0.7)
---> Maximum number of splits: floor(n/2) = 0
---> WARNING: number of splits nSplit > 0
---> WARNING: using maximum number of splits: nSplit = 0
Error in fastCor(t(exp)) : invalid nSplit: 0


My dataset is like this:

> dim(data)
[1] 4373 2655

> data[1:5,1:4]
       JCD10F36.PL2.Cell.370 JCD10F36.PL2.Cell.205 JCD10F36.PL2.Cell.374
DPM1                       0                     0                     0
FUCA2                      0                     0                     0
GCLC                       0                     0                     0
ENPP4                      0                     0                     0
ANKIB1                     0                     0                     0
       JCD10F36.PL2.Cell.375
DPM1                0.000000
FUCA2               0.000000
GCLC                0.000000
ENPP4               0.000000
ANKIB1              1.929464


My dataset is based on single-cell RNAseq experiment ; not sure if this is problematic as we have lots of zero's and the expression levels are mostly 1 or around that.

I also noticed that in the 'example_data' test run, the output gives only 10 cell types; Is this the max of cell types one can get or the package covers all known cell types but gives output assignment based on the dataset?

Thanks a lot for your help!

Best,
natlasy

**Comment by ajitjohnson** [comment]
Hi Natlasy,
That's great. I'm sorry this package is not for single-cell RNA Seq data. This package is for deconvoluting bulk transcriptomics data. I presume you are trying to identify cell types in your data. I would recommend using packages like Seurat or Scanpy. Not sure if there is an automated method available.

**Comment by natlasy** [comment]
All right. I see. Thanks indeed for your follow up and help.

Cheers,
natlasy

**Comment by ajitjohnson** [comment]
No Problem. All the best.
