### ISSUE TITLE
Showing NA in certain cell types while applying ImSig on scRNA-seq data

### ISSUE THREAD

**Issue by denoqo** [ajitjohnson/imsig#13]
Hi Ajit,

I met some problem while applying ImSig on scRNA-seq data with the ImSig R-package.
The input data I was using is PBMC scRNA-seq data (scran normalize). (~10K cells)

I don't why the T-cell columns is all NA. There should be T-cell in PBMC data.

Here are screenshot of the result:
[![Picture1.png](https://i.postimg.cc/2Sp0RGnK/Picture1.png)](https://postimg.cc/1fHGDpCG)

Thank you for your time!

**Comment by denoqo** [comment]
Until I tried to lower the correlation threshold to 0.2, I got the T cell showed up. But the results doesn't look well.
(The data are CPM normalized and scaled.)

[![Snipaste-2020-09-02-03-30-15.png](https://i.postimg.cc/dthj6Hnp/Snipaste-2020-09-02-03-30-15.png)](https://postimg.cc/tYH6CzKN)

**Comment by ajitjohnson** [comment]
Resolved outside of github
