### ISSUE TITLE
could not find function "corr_matrix"

### ISSUE THREAD

**Issue by axitamm** [ajitjohnson/imsig#2]
Hi Ajit,

All functions work fine using example_data, and I am able to use the package (excellent package, btw). However, the corr_matrix function doesn't work. 

> corr_matrix(example_data, r = 0.6)
Error in corr_matrix(example_data, r = 0.6) : 
  could not find function "corr_matrix"

Any idea what I'm doing wrong?

(Windows 7, R 3.5.1, imsig package ver 1.0)

**Comment by ajitjohnson** [comment]
Hi axitamm,

Thank you. The 'corr_matrix' is a function that can be only used by other functions and not available for users to call. Sorry. Hope that helps.

**Comment by axitamm** [comment]
Got it! Thanks!
