### ISSUE TITLE
"plot_network" error

### ISSUE THREAD

**Issue by venkataddala** [ajitjohnson/imsig#5]
Hey, 
I'm facing "Error in cor_data[fg, fg] : subscript out of bounds" error while using plot_network. Please help!

**Comment by venkataddala** [comment]
example dataset works brilliant!

> head(nexp)
 AB..9869 MIST16 MIST18 MIST1 MIST25 MIST33 MIST34 MIST35 MIST42 MIST45 MIST46 MIST56 MIST58
TSPAN6       4.96   1.35   5.26  1.19   3.28   2.38   6.51   1.36   1.77   2.38   1.53   0.36   1.51
TNMD         0.00   0.03   0.09  0.02   0.00   0.01   2.47   0.09   0.02   0.00   0.00   0.00   0.00
DPM1         8.39   2.87   7.62  4.40   4.01   5.64   8.88   7.74   4.08  10.21   1.80   0.76   3.18
SCYL3        1.27   1.07   1.79  1.11   1.06   1.17   1.58   1.12   1.68   1.44   0.54   0.34   0.51
C1orf112     1.94   0.64   2.63  0.77   0.77   1.07   2.00   1.37   0.47   0.74   0.59   0.26   0.37
FGR          0.21   4.16   1.29  1.14   3.11   1.95   0.98   3.14   0.49  13.13   0.47   1.08   0.56

**Comment by ajitjohnson** [comment]
It looks fine. Do the other functions work? <br>
``` gene_stat (exp = nexp, r = 0.7) ``` <br>
or <br>
``` imsig (exp = exp, r = 0.7) ``` <br>
Also try checking if there any dublicates in your rownames.

**Comment by JoKPro** [comment]
Hello!
I am having the same problem, everything works fine until `plot_network`.

![Unbenannt](https://user-images.githubusercontent.com/57229241/119398907-85485500-bcd8-11eb-8d3d-90c8d40bfbcc.PNG)

Would love to hear back from you!
