### ISSUE TITLE
which data does plot_network rely on?

### ISSUE THREAD

**Issue by NiRuff** [ajitjohnson/imsig#6]
Greetings,

I wanted to use all relevant information to do the plotting outside of R. 
So I thought the relevant data would be:

1. The matrix returned by the imsig function to assign the group to the nodes

2. The corr_matrix for the edges between the nodes (genes).

After I found out the corr_matrix can only be used by the other functions inside the imsig package I'm wondering whether my thoughts about network building are correct (that using exactely these two tables is sufficient) and whether there is any other possibility to extract those data for computing the edges.

Best regards,
Nicolas

**Comment by ajitjohnson** [comment]
Hi Nocolas,

Are you trying to plot a network graph (gene-gene) outside of the package? In which case you can simply calculate the correlation matrix yourself. It is simply a Pearson correlation calculated between every gene in the imsig signature. You could download the supplemental file from the paper which has this information (which genes represent which cell type).

**Comment by NiRuff** [comment]
Yes, the idea was to be able to plot outside of the ImSig package.

Okay great, so nodes are genes, edges are defined by the genes correlation and furthermore you assigned colors to the nodes (genes) by their signature, which is given in the supplemental tables.

Thank you very much!
