### ISSUE TITLE
What does the time clarification add?

### ISSUE THREAD

**Issue by willemdek11** [ajitjohnson/imsig#7]
Hi,

I'm using the imsig_survival and plot_survival functions, but the addition of the time variable doesn't change the outcome of the test.

Is this how it supposed to be?

Thanks,
Willem

**Comment by ajitjohnson** [comment]
Hi Willem,

Survival function cannot work without the time (time to event). Can you explain a bit more?

**Comment by willemdek11** [comment]
Never mind, I found the answer already by looking into the function. Thanks anyway!
